/*Test Case 6 - 

Go to "http://automationbykrishna.com/#"
Navigate to Basic Elements tab
Navigate to the Basic Forms scetion and enter the email address and password 
Click on Submit button
Validate the success alert message.
Accept the alert*/
package shreyaG.Assignment_5;

import org.openqa.selenium.Alert;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;

import base.PredefinedActions;

public class TestCase6 {

	public static void main(String[] args) throws InterruptedException {
		WebDriver driver = PredefinedActions.start();
		System.out.println("Click on basic element");
		driver.findElement(By.id("basicelements")).click();
		Thread.sleep(2000);
		
		System.out.println("Navigate to basic form section ");
		System.out.println("Enter email address");
		driver.findElement(By.xpath("//input[@id='exampleInputEmail1']")).sendKeys("rajasvim@234");
		
		System.out.println("Enter password");
		driver.findElement(By.id("pwd")).sendKeys("Pwd@567");
		
		System.out.println("Click on submit button");
		Thread.sleep(2000);
		driver.findElement(By.id("submitb2")).click();
		
		System.out.println("Switch to alert");
		Alert alert=driver.switchTo().alert();
		Thread.sleep(3000);
		
		System.out.println("Validate alert message");
		String text=alert.getText();
		String expectedText="You successfully clicked on it";
		
		if(text.equals(expectedText))
			System.out.println("Message generated by alert is correct");
		alert.accept();
		Thread.sleep(2000);
		System.out.println("Test runs successfully");
		driver.close();
		
	}

}
